name: fineartsociety
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: 4.2.1
  url_launcher: ^6.0.13
  shared_preferences: ^2.2.2
  loading_animation_widget: ^1.2.0+4
  timer_count_down: ^2.2.2
  flutter_svg: ^2.0.9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flutter_icon_snackbar: ^1.1.4
  flutter_rating_bar: ^4.0.1
  getwidget: ^4.0.0
  page_view_dot_indicator: ^2.3.0
  another_transformer_page_view: ^2.0.1
  google_maps_flutter: ^2.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true

  assets:
  
    - assets/
    # Add paths to all artist images
  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel.ttf
